server:
  port: 9624
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.simplify.model.entity
spring:
  datasource:
    username: root
    password: lb962464.
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=UTC
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
