server:
  port: 9624
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.simplify.model.entity,com.simplify.model.dto
# 指定log4j2作为日志记录
logging:
  level:
    #这个指定你的dao层，也就是mapper文件的所在包
    com.simplify.mapper: DEBUG

spring:
  datasource:
    username: persuasible
    password: 962464
    url: jdbc:oracle:thin:@47.106.177.220:1521:orcl
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

