server:
  port: 9624
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.simplify.model.entity,com.simplify.model.dto
spring:
  datasource:
    username: persuasible
    password: 962464
    url: jdbc:oracle:thin:@47.106.177.220:1521:orcl
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
